export const themeConfig = {
  themes: {
    stone: {
      name: "Stone Path",
      icon: "stone",
      bgColor: "bg-stone-50",
      textColor: "text-stone-900",
      borderColor: "border-stone-200",
      cardBgColor: "bg-stone-100",
      cardTextColor: "text-stone-800",
      cardBorderColor: "border-stone-200",
      activeBtn: "bg-stone-900 border-stone-500 text-stone-50",
      inactiveBtn: "bg-stone-200 text-stone-900 hover:bg-stone-300 border-stone-300",
      activeText: "text-stone-50",
      inactiveText: "text-stone-300 hover:text-stone-50",
      primaryBtnBgColor: "#78716c",
      primaryBtnTextColor: "#ffffff",
      primaryBtnHoverBgColor: "#44403c",
      primaryBtnHoverTextColor: "#ffffff",
      primaryBgColor: "bg-stone-800",
      primaryTextColor: "text-stone-800",
      secondaryBgColor: "bg-stone-100",
      secondaryTextColor: "text-stone-100",
      accentColor: "bg-amber-600",
      navBgColor: "bg-stone-800",
      navTextColor: "text-stone-50",
      footerBgColor: "bg-stone-800",
      footerTextColor: "text-stone-200",
      inputBgColor: "bg-white",
      inputTextColor: "text-stone-900",
      dangerColor: "text-red-600",
      dangerBgColor: "bg-red-100",
      warningColor: "text-amber-600",
      warningBgColor: "bg-amber-100",
      successColor: "text-green-600",
      successBgColor: "bg-green-100",
      scrollbarThumbColor: "#d6d3d1",
      scrollbarTrackColor: "#f5f5f4",
      scrollbarThumbHoverColor: "#a8a29e"
    },
    light: {
      name: "Sunny Day",
      icon: "sun",
      bgColor: "bg-amber-50",
      textColor: "text-amber-900",
      borderColor: "border-amber-200",
      cardBgColor: "bg-amber-100",
      cardTextColor: "text-amber-900",
      cardBorderColor: "border-amber-200",
      activeBtn: "bg-amber-700 border-amber-500 text-amber-50",
      inactiveBtn: "bg-amber-200 text-amber-900 hover:bg-amber-300 border-amber-300",
      activeText: "text-amber-50",
      inactiveText: "text-amber-300 hover:text-amber-50",
      primaryBtnBgColor: "#f59e0b",
      primaryBtnTextColor: "#ffffff",
      primaryBtnHoverBgColor: "#b45309",
      primaryBtnHoverTextColor: "#ffffff",
      primaryBgColor: "bg-amber-800",
      primaryTextColor: "text-amber-800",
      secondaryBgColor: "bg-amber-100",
      secondaryTextColor: "text-amber-100",
      accentColor: "bg-amber-600",
      navBgColor: "bg-amber-800",
      navTextColor: "text-amber-50",
      footerBgColor: "bg-amber-800",
      footerTextColor: "text-amber-200",
      inputBgColor: "bg-white",
      inputTextColor: "text-amber-900",
      dangerColor: "text-red-700",
      dangerBgColor: "bg-red-100",
      warningColor: "text-amber-700",
      warningBgColor: "bg-amber-100",
      successColor: "text-green-700",
      successBgColor: "bg-green-100",
      scrollbarThumbColor: "#fcd34d",
      scrollbarTrackColor: "#fef3c7",
      scrollbarThumbHoverColor: "#f59e0b"
    },
    dark: {
      name: "Midnight",
      icon: "moon",
      bgColor: "bg-slate-900",
      textColor: "text-slate-50",
      borderColor: "border-slate-700",
      cardBgColor: "bg-slate-800",
      cardTextColor: "text-slate-50",
      cardBorderColor: "border-slate-700",
      activeBtn: "bg-slate-700 border-slate-500 text-slate-50",
      inactiveBtn: "bg-slate-300 text-slate-900 hover:bg-slate-400 border-slate-400",
      activeText: "text-slate-50",
      inactiveText: "text-slate-300 hover:text-slate-50",
      primaryBtnBgColor: "#f8fafc",
      primaryBtnTextColor: "#0f172a",
      primaryBtnHoverBgColor: "#334155",
      primaryBtnHoverTextColor: "#f8fafc",
      primaryBgColor: "bg-slate-800",
      primaryTextColor: "text-slate-800",
      secondaryBgColor: "bg-slate-100",
      secondaryTextColor: "text-slate-100",
      accentColor: "bg-blue-600",
      navBgColor: "bg-slate-900",
      navTextColor: "text-slate-50",
      footerBgColor: "bg-slate-800",
      footerTextColor: "text-slate-200",
      inputBgColor: "bg-slate-100",
      inputTextColor: "text-slate-900",
      dangerColor: "text-red-400",
      dangerBgColor: "bg-red-900 bg-opacity-50",
      warningColor: "text-amber-400",
      warningBgColor: "bg-amber-900 bg-opacity-50",
      successColor: "text-green-400",
      successBgColor: "bg-green-900 bg-opacity-50",
      scrollbarThumbColor: "#475569",
      scrollbarTrackColor: "#1e293b",
      scrollbarThumbHoverColor: "#64748b"
    },
    cupcake: {
      name: "Sweet Cupcake",
      icon: "cupcake",
      bgColor: "bg-pink-50",
      textColor: "text-pink-900",
      borderColor: "border-pink-200",
      cardBgColor: "bg-pink-100",
      cardTextColor: "text-pink-900",
      cardBorderColor: "border-pink-200",
      activeBtn: "bg-pink-700 border-pink-500 text-pink-50",
      inactiveBtn: "bg-pink-200 text-pink-900 hover:bg-pink-300 border-pink-300",
      activeText: "text-pink-50",
      inactiveText: "text-pink-300 hover:text-pink-50",
      primaryBtnBgColor: "#be185d",
      primaryBtnTextColor: "#ffffff",
      primaryBtnHoverBgColor: "#9d174d",
      primaryBtnHoverTextColor: "#ffffff",
      primaryBgColor: "bg-pink-800",
      primaryTextColor: "text-pink-800",
      secondaryBgColor: "bg-pink-100",
      secondaryTextColor: "text-pink-100",
      accentColor: "bg-amber-600",
      navBgColor: "bg-pink-800",
      navTextColor: "text-pink-50",
      footerBgColor: "bg-pink-800",
      footerTextColor: "text-pink-200",
      inputBgColor: "bg-white",
      inputTextColor: "text-pink-900",
      dangerColor: "text-red-500",
      dangerBgColor: "bg-red-100",
      warningColor: "text-yellow-500",
      warningBgColor: "bg-yellow-100",
      successColor: "text-green-500",
      successBgColor: "bg-green-100",
      scrollbarThumbColor: "#f472b6",
      scrollbarTrackColor: "#fce7f3",
      scrollbarThumbHoverColor: "#ec4899"
    },
    forest: {
      name: "Mystic Forest",
      icon: "leaf",
      bgColor: "bg-emerald-50",
      textColor: "text-emerald-900",
      borderColor: "border-emerald-200",
      cardBgColor: "bg-emerald-100",
      cardTextColor: "text-emerald-900",
      cardBorderColor: "border-emerald-200",
      activeBtn: "bg-emerald-700 border-emerald-500 text-emerald-50",
      inactiveBtn: "bg-emerald-200 text-emerald-900 hover:bg-emerald-300 border-emerald-300",
      activeText: "text-white",
      inactiveText: "text-emerald-300 hover:text-emerald-50",
      primaryBtnBgColor: "#047857",
      primaryBtnTextColor: "#ffffff",
      primaryBtnHoverBgColor: "#065f46",
      primaryBtnHoverTextColor: "#ffffff",
      primaryBgColor: "bg-emerald-800",
      primaryTextColor: "text-emerald-800",
      secondaryBgColor: "bg-emerald-100",
      secondaryTextColor: "text-emerald-100",
      accentColor: "bg-amber-600",
      navBgColor: "bg-emerald-800",
      navTextColor: "text-emerald-50",
      footerBgColor: "bg-emerald-800",
      footerTextColor: "text-emerald-200",
      inputBgColor: "bg-white",
      inputTextColor: "text-emerald-900",
      dangerColor: "text-red-500",
      dangerBgColor: "bg-red-100",
      warningColor: "text-yellow-500",
      warningBgColor: "bg-yellow-100",
      successColor: "text-green-500",
      successBgColor: "bg-green-100",
      scrollbarThumbColor: "#34d399",
      scrollbarTrackColor: "#d1fae5",
      scrollbarThumbHoverColor: "#10b981"
    },
    ocean: {
      name: "Deep Ocean",
      icon: "water",
      bgColor: "bg-blue-50",
      textColor: "text-blue-900",
      borderColor: "border-blue-200",
      cardBgColor: "bg-blue-100",
      cardTextColor: "text-blue-900",
      cardBorderColor: "border-blue-200",
      activeBtn: "bg-blue-700 border-blue-500 text-blue-50",
      inactiveBtn: "bg-blue-200 text-blue-900 hover:bg-blue-300 border-blue-300",
      activeText: "text-blue-50",
      inactiveText: "text-blue-300 hover:text-blue-50",
      primaryBtnBgColor: "#2563eb",
      primaryBtnTextColor: "#ffffff",
      primaryBtnHoverBgColor: "#1d4ed8",
      primaryBtnHoverTextColor: "#ffffff",
      primaryBgColor: "bg-blue-800",
      primaryTextColor: "text-blue-800",
      secondaryBgColor: "bg-blue-100",
      secondaryTextColor: "text-blue-100",
      accentColor: "bg-amber-600",
      navBgColor: "bg-blue-800",
      navTextColor: "text-blue-50",
      footerBgColor: "bg-blue-800",
      footerTextColor: "text-blue-200",
      inputBgColor: "bg-white",
      inputTextColor: "text-blue-900",
      dangerColor: "text-red-500",
      dangerBgColor: "bg-red-100",
      warningColor: "text-yellow-500",
      warningBgColor: "bg-yellow-100",
      successColor: "text-green-500",
      successBgColor: "bg-green-100",
      scrollbarThumbColor: "#60a5fa",
      scrollbarTrackColor: "#dbeafe",
      scrollbarThumbHoverColor: "#3b82f6"
    }
  },
};