export const themeConfig = {
  themes: {
    light: {
      bg: "bg-stone-50",
      text: "text-stone-700",
      cardBg: "bg-stone-100",
      cardText: "text-stone-800",
      inputBg: "bg-white",
      inputText: "text-stone-800",
      inputBorder: "border-stone-300",
      btnBg: "bg-stone-50 hover:bg-stone-300 shadow-none",
      active: "bg-stone-500 text-stone-50 shadow-none",
      inactive: "bg-stone-100 text-stone-800 shadow-none hover:bg-stone-200",
    },
    dark: {
      bg: "bg-gray-900",
      text: "text-white",
      cardBg: "bg-gray-800",
      cardText: "text-white",
      inputBg: "bg-gray-700",
      inputText: "text-gray-50",
      inputBorder: "border-gray-300",
      btnBg: "bg-gray-50 hover:bg-gray-300 shadow-none",
      active: "bg-white text-gray-900 shadow-none",
      inactive: "bg-transparent text-white shadow-none hover:bg-white hover:text-gray-900",
    },
    cupcake: {
      bg: "bg-pink-50",
      text: "text-gray-700",
      cardBg: "bg-pink-100",
      cardText: "text-gray-700",
      inputBg: "bg-white",
      inputText: "text-gray-700",
      inputBorder: "border-pink-300",
      btnBg: "bg-pink-50 hover:bg-pink-300 shadow-none",
      active: "bg-pink-500 text-pink-50 shadow-none",
      inactive: "bg-pink-100 text-pink-700 shadow-none hover:bg-pink-200",
    },
    forest: {
      bg: "bg-green-50",
      text: "text-green-700",
      cardBg: "bg-green-100",
      cardText: "text-green-800",
      inputBg: "bg-white",
      inputText: "text-green-800",
      inputBorder: "border-green-300",
      btnBg: "bg-green-50 hover:bg-green-300 shadow-none",
      active: "bg-green-500 text-green-50 shadow-none",
      inactive: "bg-green-100 text-green-800 shadow-none hover:bg-green-200",
    },
    luxury: {
      bg: "bg-yellow-50",
      text: "text-yellow-700",
      cardBg: "bg-yellow-100",
      cardText: "text-yellow-800",
      inputBg: "bg-white",
      inputText: "text-yellow-800",
      inputBorder: "border-yellow-300",
      btnBg: "bg-yellow-50 hover:bg-yellow-300 shadow-none",
      active: "bg-yellow-500 text-yellow-50 shadow-none",
      inactive: "bg-yellow-100 text-yellow-800 shadow-none hover:bg-yellow-200",
    },
  },
};